//! End-to-end check that the whisper.cpp backend actually transcribes audio.
//!
//! The unit tests in `backends::whisper_cpp` cover buffering arithmetic and
//! error messages, which is everything reachable without the native library.
//! None of them prove a single word comes out, and "the tests pass while the
//! feature is dead" is the failure mode this file exists to close.
//!
//! Run it with:
//!
//! ```text
//! cargo test -p asr --features whisper
//! ```
//!
//! Weights are not in the repository (142MiB, and the project vendors no
//! model). The test looks for a ggml model in this order:
//!
//! 1. `$OUTLOUD_WHISPER_MODEL`
//! 2. `~/.outloud/models/whisper-base.en`, where `asr::models::fetch` puts
//!    the `whisper-base.en` registry entry.
//!
//! With neither present the test reports the fix and passes, so a clone
//! without weights still gets a green suite. CI that wants the real
//! assertion sets `OUTLOUD_WHISPER_MODEL`.

#![cfg(feature = "whisper")]

use asr::Recognizer;

/// 16-bit PCM mono WAV reader. The fixture is generated by the project (see
/// docs/investigations/whisper-spike.md), so supporting exactly that format
/// is enough and keeps the crate free of an audio-decoding dependency.
fn read_wav_16k_mono(path: &std::path::Path) -> Vec<f32> {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let data_at = bytes
        .windows(4)
        .position(|w| w == b"data")
        .expect("no data chunk in fixture")
        + 8;
    bytes[data_at..]
        .chunks_exact(2)
        .map(|c| i16::from_le_bytes([c[0], c[1]]) as f32 / 32768.0)
        .collect()
}

fn model_path() -> Option<std::path::PathBuf> {
    if let Some(p) = std::env::var_os("OUTLOUD_WHISPER_MODEL") {
        let p = std::path::PathBuf::from(p);
        assert!(
            p.exists(),
            "OUTLOUD_WHISPER_MODEL points at {}, which does not exist",
            p.display()
        );
        return Some(p);
    }
    let cached = asr::models::default_cache_dir().join("whisper-base.en");
    cached.exists().then_some(cached)
}

#[test]
fn transcribes_the_fixture_recording() {
    let Some(model) = model_path() else {
        eprintln!(
            "skipping: no whisper model. Fetch one with\n  \
             curl -L -o ~/.outloud/models/whisper-base.en \\\n    \
             https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin\n\
             or set OUTLOUD_WHISPER_MODEL to a ggml .bin."
        );
        return;
    };

    let wav = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata")
        .join("quick-brown-fox.wav");
    let samples = read_wav_16k_mono(&wav);
    let audio_secs = samples.len() as f32 / 16_000.0;
    assert!(audio_secs > 1.0, "fixture is only {audio_secs:.2}s");

    let mut rec =
        asr::backends::whisper_cpp::WhisperCppRecognizer::new(&model).expect("model should load");

    // Fed in 200ms chunks, the way the segmenter delivers audio, so this also
    // covers the buffering path rather than one giant slice the daemon never
    // produces.
    let chunk = (0.2 * 16_000.0) as usize;
    for c in samples.chunks(chunk) {
        assert!(
            rec.feed(c).is_none(),
            "whisper is a finalizer: it must not emit partials"
        );
    }

    let started = std::time::Instant::now();
    let out = rec.finalize().expect("finalize should succeed");
    let elapsed = started.elapsed();

    // Compared case- and punctuation-insensitively: whisper's capitalisation
    // and trailing period are model choices that can shift between versions,
    // while the words are what the user reads.
    let normalized: String = out
        .text
        .to_lowercase()
        .chars()
        .filter(|c| c.is_alphanumeric() || c.is_whitespace())
        .collect();
    let normalized = normalized.split_whitespace().collect::<Vec<_>>().join(" ");
    assert_eq!(
        normalized, "the quick brown fox jumps over the lazy dog",
        "got {:?} in {elapsed:?}",
        out.text
    );

    assert!(
        (out.audio_secs - audio_secs).abs() < 0.01,
        "reported {:.2}s for {audio_secs:.2}s of audio",
        out.audio_secs
    );
    assert!(
        out.words.is_empty(),
        "this backend documents word timings as unavailable"
    );

    // finalize must leave the instance reusable for the next utterance.
    let again = rec.finalize().expect("a reset recognizer finalizes empty");
    assert!(again.text.is_empty(), "state leaked: {:?}", again.text);

    eprintln!("whisper finalize: {elapsed:?} for {audio_secs:.2}s of audio");
}

/// An utterance longer than whisper's 30s encoder window must keep the
/// START of the audio.
///
/// Keeping the end instead would drop the beginning of a long sentence, and
/// a transcript that begins mid-thought reads as a recognition failure
/// rather than a length limit. The backend documents that choice; nothing
/// asserted it, and the only evidence a user gets is one stderr line.
#[test]
fn an_over_long_utterance_keeps_the_beginning() {
    let Some(model) = model_path() else {
        eprintln!("skipping: no whisper model");
        return;
    };
    let wav = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata")
        .join("quick-brown-fox.wav");
    let speech = read_wav_16k_mono(&wav);

    let mut rec =
        asr::backends::whisper_cpp::WhisperCppRecognizer::new(&model).expect("model should load");
    rec.feed(&speech);
    // Pad past the window with silence. 40s total: the sentence is inside
    // the first 30s, so a backend that kept the END would transcribe pure
    // silence and return nothing.
    let padding = vec![0.0f32; 16_000 * 40 - speech.len()];
    rec.feed(&padding);

    let out = rec.finalize().expect("finalize should succeed");
    let normalized: String = out
        .text
        .to_lowercase()
        .chars()
        .filter(|c| c.is_alphanumeric() || c.is_whitespace())
        .collect();
    assert!(
        normalized.contains("quick brown fox"),
        "the first 30s must survive truncation, got {:?}",
        out.text
    );
    // audio_secs reports what the user actually said, not the truncated
    // window: it is the length of their utterance, and the truncation is a
    // separate fact reported on stderr.
    assert!(
        (out.audio_secs - 40.0).abs() < 0.1,
        "reported {:.2}s for 40s of audio",
        out.audio_secs
    );
}
