#!/usr/bin/env bash
# Windows packaging: portable zip, NSIS installer, optional MSI (WiX), and
# Authenticode signing. Runs under Git Bash / MSYS on a Windows runner, which
# is why it is bash like every other script here (one language, one lint).
#
# WHY NSIS as the primary installer and MSI as secondary: NSIS produces a
# small self-contained installer with no runtime prerequisites and is what
# most Rust desktop tools ship (including Handy via Tauri). MSI matters for
# enterprise deployment (GPO/Intune push), so we emit it when WiX is present
# but do not fail the release when it is not.
#
# Authenticode / SmartScreen reality check, documented here because it is a
# business decision as much as a technical one:
#   - An UNSIGNED exe gets the harshest SmartScreen wall and some AVs
#     quarantine it outright. Not shippable.
#   - An OV certificate signs validly but SmartScreen reputation starts at
#     zero PER CERTIFICATE and builds with install volume over weeks. Early
#     users still click through "More info -> Run anyway".
#   - An EV certificate (or the newer Azure Trusted Signing service) grants
#     reputation immediately. For a tool that injects input - exactly the
#     behaviour malware heuristics look for - EV/Trusted Signing is the only
#     path that avoids weeks of scary warnings. Budget it like the Apple
#     Developer ID: an onboarding cost, not a distribution nicety.
#
# Signing env (CI provides via secrets; absent locally -> unsigned artifacts,
# clearly labelled):
#   WINDOWS_CERT_THUMBPRINT  thumbprint of a cert in the runner's cert store
#                            (imported by the workflow from a base64 secret),
#                            signed via signtool /sha1.
#
# The pre-Haswell AVX2 crash class: nothing in THIS script guards it because
# the guard belongs earlier, at compile time. See .cargo/config.toml (no
# target-cpu raise anywhere) and deny.toml (bans `ort`'s prebuilt runtime).
# ci-verify-baseline.sh disassembles the shipped exe to prove no AVX2 leaked
# into static initializers. docs/build-and-release.md#windows has the story.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

TARGET="${1:-x86_64-pc-windows-msvc}"   # or aarch64-pc-windows-msvc
VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -1)"
OUT="dist/windows/$TARGET"
BIN="target/$TARGET/release/spike-cli.exe"
# The dictation daemon: the thing a user actually runs. It is a separate
# artifact from the spike harness because they answer different questions
# ("does this machine work" vs "dictate for me"), and shipping only the
# harness, as this script did while the Windows backends were stubs, would
# mean a Windows release that cannot dictate.
DAEMON="target/$TARGET/release/aquad.exe"

echo "==> Building $TARGET"
rustup target add "$TARGET"
cargo build --release --locked --package spike-cli --package aquad --target "$TARGET"

mkdir -p "$OUT"
cp "$BIN" "$OUT/aqua-spike.exe"
cp "$DAEMON" "$OUT/aquad.exe"

sign() {
    local file="$1"
    if [ -n "${WINDOWS_CERT_THUMBPRINT:-}" ]; then
        echo "==> Authenticode signing $file"
        # /fd sha256: SHA-1 signatures are rejected by modern Windows.
        # /td sha256 /tr: RFC3161 timestamp so the signature outlives the
        # certificate. Without a timestamp, every shipped binary breaks the
        # day the cert expires.
        signtool sign /sha1 "$WINDOWS_CERT_THUMBPRINT" /fd sha256 \
            /tr http://timestamp.digicert.com /td sha256 "$file"
        signtool verify /pa "$file"
    else
        echo "==> WINDOWS_CERT_THUMBPRINT unset: NOT signing $file (SmartScreen will wall this build)"
    fi
}

sign "$OUT/aqua-spike.exe"
sign "$OUT/aquad.exe"

echo "==> Portable zip"
(cd "$OUT" && 7z a -tzip "aqua-spike-$VERSION-$TARGET.zip" aqua-spike.exe aquad.exe >/dev/null)

if command -v makensis >/dev/null 2>&1; then
    echo "==> NSIS installer"
    cat > "$OUT/installer.nsi" <<NSIS
; Generated by build-windows.sh. Minimal by design: install, uninstall,
; PATH entry. No services, no autostart - a spike harness must not persist.
!include "MUI2.nsh"
Name "Aqua OSS Spike"
OutFile "aqua-spike-$VERSION-$TARGET-setup.exe"
InstallDir "\$LOCALAPPDATA\\AquaSpike"
RequestExecutionLevel user   ; per-user install: no UAC prompt, no admin
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"
Section "Install"
    SetOutPath "\$INSTDIR"
    File "aqua-spike.exe"
    File "aquad.exe"
    WriteUninstaller "\$INSTDIR\\uninstall.exe"
    WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\AquaSpike" "DisplayName" "Aqua OSS Spike"
    WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\AquaSpike" "UninstallString" "\$INSTDIR\\uninstall.exe"
SectionEnd
Section "Uninstall"
    Delete "\$INSTDIR\\aqua-spike.exe"
    Delete "\$INSTDIR\\aquad.exe"
    Delete "\$INSTDIR\\uninstall.exe"
    RMDir "\$INSTDIR"
    DeleteRegKey HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\AquaSpike"
SectionEnd
NSIS
    (cd "$OUT" && makensis installer.nsi)
    sign "$OUT/aqua-spike-$VERSION-$TARGET-setup.exe"
else
    echo "==> makensis not found: skipping NSIS installer"
fi

if command -v wix >/dev/null 2>&1; then
    echo "==> MSI via WiX v4"
    cat > "$OUT/package.wxs" <<WXS
<?xml version="1.0" encoding="UTF-8"?>
<!-- Minimal per-user MSI for enterprise deployment tooling. UpgradeCode is
     fixed forever: changing it orphans installed copies from upgrades. -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package Name="Aqua OSS Spike" Manufacturer="aquaoss" Version="$VERSION"
           UpgradeCode="7f9b2a44-1c3e-4d5f-9a8b-0e6f31c25a10" Scope="perUser">
    <MajorUpgrade DowngradeErrorMessage="A newer version is already installed." />
    <StandardDirectory Id="LocalAppDataFolder">
      <Directory Id="INSTALLFOLDER" Name="AquaSpike">
        <Component Id="MainExe">
          <File Source="aqua-spike.exe" />
          <RegistryValue Root="HKCU" Key="Software\\AquaSpike" Name="installed"
                         Type="integer" Value="1" KeyPath="yes" />
        </Component>
        <Component Id="DaemonExe">
          <File Source="aquad.exe" />
          <RegistryValue Root="HKCU" Key="Software\\AquaSpike" Name="daemon"
                         Type="integer" Value="1" KeyPath="yes" />
        </Component>
      </Directory>
    </StandardDirectory>
    <Feature Id="Main"><ComponentRef Id="MainExe" /><ComponentRef Id="DaemonExe" /></Feature>
  </Package>
</Wix>
WXS
    (cd "$OUT" && wix build package.wxs -o "aqua-spike-$VERSION-$TARGET.msi")
    sign "$OUT/aqua-spike-$VERSION-$TARGET.msi"
else
    echo "==> wix not found: skipping MSI (NSIS installer is the primary artifact)"
fi

ls -l "$OUT"
